# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


platform :ios, '9.2'
pod 'CocoaLumberjack/Swift'
pod 'CocoaAsyncSocket'  

pod 'ProxyKit'    
pod 'ProxyKit/Server' # Just the server code
# pod 'ProxyKit/Client' # Just the client code

use_frameworks!


target 'Netcon-iOS' do

end

target 'Netcon-iOS' do

end

